historialclinico/api/urls.py
from django.conf.urls import url
from django.urls import path, include

from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'api'
urlpatterns = [
    url(r'^empleado/$', views.CrearEmpleadoView.as_view(), name="create"),
    url(r'^empleado/(?P<pk>[0-9]+)/$', views.ListaEmpleadoView.as_view(), name="details"),
    url(r'^consultaMedica/$', views.CrearConsultaMedicaView.as_view(), name="create"),
    url(r'^consultaMedica/(?P<pk>[0-9]+)/$', views.ListaConsultaMedicaView.as_view(), name="details"),
    url(r'^atencionEnfermeria/$', views.CrearAtencionEnfermeriaView.as_view(), name="create"),
    url(r'^atencionEnfermeria/(?P<pk>[0-9]+)/$', views.ListaAtencionEnfermeriaView.as_view(), name="details"),
    url(r'^signosVitales/$', views.CrearSignosVitalesView.as_view(), name="create"),
    url(r'^signosVitales/(?P<pk>[0-9]+)/$', views.ListaSignosVitalesView.as_view(), name="details"),
    url(r'^enfermedad/$', views.CrearEnfermedadView.as_view(), name="create"),
    url(r'^enfermedad/(?P<pk>[0-9]+)/$', views.ListaEnfermedadView.as_view(), name="details"),
    url(r'^diagnostico/$', views.CrearDiagnosticoView.as_view(), name="create"),
    url(r'^diagnostico/(?P<pk>[0-9]+)/$', views.ListaDiagnosticoView.as_view(), name="details"),
    url(r'^permisoMedico/$', views.CrearPermisoMedicoView.as_view(), name="create"),
    url(r'^permisoMedico/(?P<pk>[0-9]+)/$', views.ListaPermisoMedicoView.as_view(), name="details"),
    url(r'^inmunizacion/$', views.CrearInmunizacionView.as_view(), name="create"),
    url(r'^inmunizacion/(?P<pk>[0-9]+)/$', views.ListaInmunizacionView.as_view(), name="details"),
    url(r'^vacuna/$', views.CrearVacunaView.as_view(), name="create"),
    url(r'^vacuna/(?P<pk>[0-9]+)/$', views.ListaVacunaView.as_view(), name="details"),
    url(r'^fichaMedica/$', views.CrearFichaMedicaView.as_view(), name="create"),
    url(r'^fichaMedica/(?P<pk>[0-9]+)/$', views.ListaFichaMedicaView.as_view(), name="details"),
    url(r'^aparatoSistema/$', views.CrearAparatoSistemaView.as_view(), name="create"),
    url(r'^aparatoSistema/(?P<pk>[0-9]+)/$', views.ListaAparatoSistemaView.as_view(), name="details"),
    url(r'^antecedentePatologicoPersonal/$', views.CrearAntecedentePatologicoPersonal.as_view(), name="create"),
    url(r'^antecedentePatologicoPersonal/(?P<pk>[0-9]+)/$', views.ListaAntecedentePatologicoPersonalView.as_view(), name="details"),
    url(r'^antecedenteGinecoObstetrico/$', views.CrearAntecedenteGinecoObstetrico.as_view(), name="create"),
    url(r'^antecedenteGinecoObstetrico/(?P<pk>[0-9]+)/$', views.ListaAntecedenteGinecoObstetricoView.as_view(), name="details"),
    url(r'^antecedente/$', views.CrearAntecedente.as_view(), name="create"),
    url(r'^antecedente/(?P<pk>[0-9]+)/$', views.ListaAntecedenteView.as_view(), name="details"),
    url(r'^habito/$', views.CrearHabito.as_view(), name="create"),
    url(r'^habito/(?P<pk>[0-9]+)/$', views.ListaHabitoView.as_view(), name="details"),
    url(r'^antecedentePatologicoFamiliar/$', views.CrearAntecedentePatologicoFamiliarView.as_view(), name="create"),
    url(r'^antecedentePatologicoFamiliar/(?P<pk>[0-9]+)/$', views.ListaAntecedentePatologicoFamiliarView.as_view(), name="details"),
    url(r'^empresa/$', views.CrearEmpresaView.as_view(), name="create"),
    url(r'^empresa/(?P<pk>[0-9]+)/$', views.ListaEmpresaView.as_view(), name="details"),
    url(r'^antecedenteLaboral/$', views.CrearAntecedenteLaboralView.as_view(), name="create"),
    url(r'^antecedenteLaboral/(?P<pk>[0-9]+)/$', views.ListaAntecedenteLaboralView.as_view(), name="details"),
    url(r'^factorRiesgo/$', views.CrearFactorRiesgoView.as_view(), name="create"),
    url(r'^factorRiesgo/(?P<pk>[0-9]+)/$', views.ListaFactorRiesgoView.as_view(), name="details"),
    url(r'^examenLaboratorio/$', views.CrearExamenLaboratorioView.as_view(), name="create"),
    url(r'^examenLaboratorio/(?P<pk>[0-9]+)/$', views.ListaExamenLaboratorioView.as_view(), name="details"),
    url(r'^somaticoGeneral/$', views.CrearSomaticoGeneralView.as_view(), name="create"),
    url(r'^somaticoGeneral/(?P<pk>[0-9]+)/$', views.ListaSomaticoGeneralView.as_view(), name="details"),
    url(r'^regional/$', views.CrearRegionalView.as_view(), name="create"),
    url(r'^regional/(?P<pk>[0-9]+)/$', views.ListaRegionalView.as_view(), name="details"),
    url(r'^columna/$', views.CrearColumnaView.as_view(), name="create"),
    url(r'^columna/(?P<pk>[0-9]+)/$', views.ListaColumnaView.as_view(), name="details"),
    url(r'^regionLumbar/$', views.CrearRegionLumbarView.as_view(), name="create"),
    url(r'^regionLumbar/(?P<pk>[0-9]+)/$', views.ListaRegionLumbarView.as_view(), name="details"),
    url(r'^extremidades/$', views.CrearExtremidadesView.as_view(), name="create"),
    url(r'^extremidades/(?P<pk>[0-9]+)/$', views.ListaExtremidadesView.as_view(), name="details"),
    url(r'^localizacion/$', views.CrearLocalizacionView.as_view(), name="create"),
    url(r'^localizacion/(?P<pk>[0-9]+)/$', views.ListaLocalizacionView.as_view(), name="details"),
    url(r'^examenFisico/$', views.CrearExamenFisicoView.as_view(), name="create"),
    url(r'^examenFisico/(?P<pk>[0-9]+)/$', views.ListaExamenFisicoView.as_view(), name="details"),
    url(r'^examenConsulta/$', views.CrearExamenConsultaView.as_view(), name="create"),
    url(r'^examenConsulta/(?P<pk>[0-9]+)/$', views.ListaExamenConsultaView.as_view(), name="details"),
    url(r'^vulnerabilidad/$', views.CrearVulnerabilidadView.as_view(), name="create"),
    url(r'^vulnerabilidad/(?P<pk>[0-9]+)/$', views.ListaVulnerabilidadView.as_view(), name="details"),
    url(r'^usuario/', views.ingresoUsuario, name="hello"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

historialclinico/historial/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'historial'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.loginUser, name='login'),
    url(r'^cerrarSesion/$', views.cerrarSesion, name='cerrarSesion'),
    url(r'^nuevo/ficha/(?P<empleado>[0-9]+)/$', views.nuevaFichaMedica, name='nuevaFichaMedica'),
    url(r'^nuevo/empleado$', views.nuevoEmpleado, name='nuevoEmpleado'),
    url(r'^crear/empleado', views.guardarEmpleado, name='guardarEmpleado'),
    url(r'^crear/ficha', views.guardarFichaMedica, name='guardarFichaMedica'),
    url(r'^info/empleado/$', views.infoEmpleado, name='infoEmpleado'),
    url(r'^consultar/ficha/(?P<empleado>[0-9]+)/$', views.consultarFicha, name='consultarFicha'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)
'''url(r'^auth-jwt/', obtain_jwt_token),
    url(r'^auth-jwt-refresh/', refresh_jwt_token),
    url(r'^auth-jwt-verify/', verify_jwt_token),'''

historialclinico/historialclinico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('historial.urls')),
    path('api/', include('api.urls'))
]
#path('rest-auth/', include('rest_auth.urls'))

historialclinico/historial/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template import loader
from django.contrib.auth.decorators import login_required
from datetime import date
from api.models import *
import time

''' Esta vista me redirige a la página principal
    Valida si existe el usuario o no'''


@login_required(login_url='/login/')
def index(request):
    template = loader.get_template('historial/index.html')
    usuario = User.objects.get(username=request.user.username)
    lista_empleados = Empleado.objects.all()
    context = {
        'usuario': usuario,
        'listaEmpleados': lista_empleados,
        'id_empleado': 0
    }
    return HttpResponse(template.render(context, request))


def loginUser(request):
    template = loader.get_template('historial/login.html')
    if(request.method == 'POST'):
        nombre = request.POST['usuario']
        clave = request.POST['password']
        usuario = authenticate(request, username=nombre, password=clave)
        if usuario is not None and not usuario.is_superuser:
            login(request, usuario)
            return redirect('historial:index')
        else:
            notice = 'Usuario y/o contraseña incorrectos'
    else:
        notice = 'none'
    context = {
        'notice': notice
    }
    return HttpResponse(template.render(context, request))

def cerrarSesion(request):
    logout(request)
    return redirect('historial:login')


'''
def mi_error_404(request):
    nombre_template = 'historial/error404.html'
    return page_not_found(request, template_name=nombre_template)'''


@login_required(login_url='/login/')
def nuevaFichaMedica(request, empleado):
    template = loader.get_template('historial/nueva_ficha_medica.html')
    usuario = User.objects.get(username=request.user.username)
    tipos_riesgos = FactorRiesgo.TIPOS
    nombres_riesgos = FactorRiesgo.NOMBRES
    tipos_ficha = FichaMedica.TIPOS
    lugares = AntecedentePatologicoPersonal.LUGARES
    fecha_ficha = date.today().strftime("%Y-%m-%d")
    nombres_vacunas = Vacuna.NOMBRES
    dosis_vacunas = Vacuna.DOSIS
    nombres_aparatos = AparatoSistema.NOMBRES
    tipos_examenes_laboratorio = ExamenLaboratorio.EXAMENES
    antecedentes = Antecedente.ANTECEDENTES
    alcohol = Habito.ALCOHOL
    tabaco = Habito.TABACO
    #id_empleado = '0'
    tipo_inicial = True
    #empleado = None
    enfermedades = Enfermedad.objects.all()
    #if (request.method == 'GET'):
        #id_empleado = request.GET.get('id_empleado')
    empleado_obj = Empleado.objects.get(id=empleado)
    id_empleado = empleado
    if(empleado_obj.ficha_actual > 0):
        tipo_inicial = False

    context = {
        'usuario': usuario,
        'tipos': tipos_riesgos,
        'nombres': nombres_riesgos,
        'fecha_ficha': fecha_ficha,
        'tipos_ficha': tipos_ficha,
        'lugares': lugares,
        'nombres_vacunas': nombres_vacunas,
        'dosis_vacunas': dosis_vacunas,
        'nombres_aparatos': nombres_aparatos,
        'tipos_examenes_laboratorio': tipos_examenes_laboratorio,
        'antecedentes': antecedentes,
        'alcohol': alcohol,
        'tabaco': tabaco,
        'empleado': empleado_obj,
        'id_empleado': id_empleado,
        'tipo_inicial': tipo_inicial,
        'enfermedades': enfermedades
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def nuevoEmpleado(request):
    template = loader.get_template('historial/nuevo_empleado.html')
    usuario = User.objects.get(username=request.user.username)
    id_empleado = 0
    if (request.method == 'POST'):
        id_empleado = request.POST.get('id_empleado')
    context = {
        'usuario': usuario,
        'id_empleado': id_empleado
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def infoEmpleado(request):
    template = loader.get_template('historial/info_empleado.html')
    usuario = User.objects.get(username=request.user.username)
    id_empleado = 0
    empleado = usuario.profile.empleado
    if (request.method == 'POST'):
        id_empleado = request.POST.get('id_empleado')
    context = {
        'usuario': usuario,
        'id_empleado': id_empleado,
        'empleado': empleado
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def consultarFicha(request, empleado):
    template = loader.get_template('historial/lista_ficha_medica_empleado.html')
    usuario = User.objects.get(username=request.user.username)
    lista_fichas_empleado = FichaMedica.objects.filter(empleado=empleado)
    empleado_obj = Empleado.objects.get(id=empleado)
    context = {
        'usuario': usuario,
        'lista_fichas_empleado': lista_fichas_empleado,
        'empleado': empleado_obj,
        'id_empleado': empleado
    }
    return HttpResponse(template.render(context, request))
'''
    Permite crear un empleado
    hace post
'''
@login_required(login_url='/login/')
def guardarEmpleado(request):
    if(request.method == 'POST'):
        nuevoEmpleado = Empleado()
        nuevoEmpleado.foto = request.POST.get('ingreso_foto')
        nuevoEmpleado.nombre = request.POST.get('nombres')
        nuevoEmpleado.apellido = request.POST.get('apellidos')
        nuevoEmpleado.cedula = request.POST.get('cedula')
        nuevoEmpleado.sexo  = request.POST.get('sexo')
        nuevoEmpleado.edad = request.POST.get('edad')
        nuevoEmpleado.estadoCivil = request.POST.get('estado_civil')
        nuevoEmpleado.lugarNacimiento = request.POST.get('lugar_nacimiento')
        nuevoEmpleado.fechaNacimiento = request.POST.get('fecha_nacimiento')
        nuevoEmpleado.correo = request.POST.get('correo')
        nuevoEmpleado.direccion = request.POST.get('direccion')
        nuevoEmpleado.instruccion = request.POST.get('instruccion')
        nuevoEmpleado.profesion = request.POST.get('profesion')
        nuevoEmpleado.ocupacion = request.POST.get('ocupacion')
        nuevoEmpleado.fechaRegistro = time.strftime("%Y-%m-%d")
        nuevoEmpleado.ficha_actual = 0
        nuevoEmpleado.save()

        return redirect('historial:index')


'''
    Permite guardar una ficha médica de un empleado
    hace post
'''
@login_required(login_url='/login/')
def guardarFichaMedica(request):
    if(request.method == 'POST'):
        id_empleado = request.POST.get('id_empleado')
        empleado = Empleado.objects.get(pk = id_empleado)

        nueva_ficha = FichaMedica()
        nueva_ficha.empleado = empleado
        nueva_ficha.inmunizacion = guardarInmunizaciones(request)
        nueva_ficha.fecha = time.strftime("%Y-%m-%d")
        nueva_ficha.ciudad = request.POST.get('ciudad_ficha')
        nueva_ficha.tipo = request.POST.get('input_ficha_hidden')
        nueva_ficha.prescripcion = request.POST.get('prescripciones_medicas')
        nueva_ficha.save()
        empleado.ficha_actual = nueva_ficha.id
        empleado.save()

        empresa_actual = Empresa()
        empresa_actual.nombre = request.POST.get('nombre_empresa_actual')
        empresa_actual.cargo = request.POST.get('cargo_actual')
        #empresa_actual.riesgos = request.POST.get('riesgos')
        empresa_actual.epps = request.POST.get('epps')
        empresa_actual.area_trabajo = request.POST.get('area_trabajo')
        empresa_actual.save()

        antecedente_laboral = AntecedenteLaboral()
        antecedente_laboral.ficha_medica = nueva_ficha
        antecedente_laboral.empresa = empresa_actual
        #antecedente_laboral.tiempo = None
        antecedente_laboral.edad_inicio = request.POST.get('edad_inicio')
        antecedente_laboral.actividades_extralaborales = request.POST.get('actividades_extralaborales')
        antecedente_laboral.actual = True
        antecedente_laboral.save()

        guardarEmpresasAnteriores(request, nueva_ficha)
        guardarAntecedentesPatologicosPersonales(request, nueva_ficha)

        planificacion = request.POST.get('planificacion_familiar')
        if(planificacion in request.POST):
            antecedente_gineco = AntecedenteGinecoObstetrico()
            antecedente_gineco.ficha = nueva_ficha
            antecedente_gineco.fecha_ultima_menstruacion = request.POST.get('fecha_ultima_menstruacion')
            antecedente_gineco.planificacion_familiar = request.POST.get('planificacion_familiar')
            antecedente_gineco.save()

            lista_gineco = request.POST.getlist('antecedente_gineco-obstetrico')
            for x in lista_gineco:
                antecedente = Antecedente()
                antecedente.antecedente_gineco_obstetrico = antecedente_gineco
                antecedente.antecedente = x
                antecedente.save()

        habito = Habito()
        habito.ficha = nueva_ficha
        habito.alcohol = request.POST.get('alcohol')
        habito.tabaco = request.POST.get('tabaco')
        if(request.POST.get('cantidad_tabaco') == ""):
            habito.cantidad_tabaco = None
        else:
            habito.cantidad_tabaco = request.POST.get('cantidad_tabaco')
        habito.save()

        guardarAntecedentesPatologicosFamiliares(request, nueva_ficha)
        guardarAparatoSistema(request, nueva_ficha)

        signos_vitales = SignosVitales()
        signos_vitales.empleado = empleado
        if (request.POST.get('presion_sistolica') == ""):
            signos_vitales.presion_sistolica = None
        else:
            signos_vitales.presion_sistolica = request.POST.get('presion_sistolica')

        if (request.POST.get('presion_distolica') == ""):
            signos_vitales.presion_distolica = None
        else:
            signos_vitales.presion_distolica = request.POST.get('presion_distolica')

        if (request.POST.get('frecuencia_cardiaca') == ""):
            signos_vitales.pulso = None
        else:

historialclinico/historial/templates/historial/base.html
<!DOCTYPE html>
<html lang="es">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <title>Historial - {% block titulo %}{% endblock %}</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/materialdesignicons.min.css' %}" rel="stylesheet">
        <link href="{% static 'fonts/materialdesignicons-webfont.eot' %}" rel="octet-stream">
        <link href="{% static 'fonts/materialdesignicons-webfont.ttf' %}" rel="octet-stream">
        <link href="{% static 'fonts/materialdesignicons-webfont.woff' %}" rel="octet-stream">
        <link href="{% static 'fonts/materialdesignicons-webfont.woff2' %}" rel="octet-stream">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        {% block estilos %}{% endblock %}
    </head>
    <body>
        <nav id="navbar_horizontal" class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/historial_logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                Historial Médico
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu_sesion" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-user">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="opciones_empleado" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Empleados
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% if empleado.ocupacion == 'Doctor' or empleado.ocupacion == 'doctor' %}
                            <a class="dropdown-item" href="{% url 'historial:nuevoEmpleado' %}">Nuevo</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'historial:index' %}">Consultar</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="opciones_reporte" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Reportes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Reporte 1</a>
                            <a class="dropdown-item" href="#">Reporte 2</a>
                        </div>
                    </li>
                </ul>
            </div>
            <div id="menu_sesion" class="collapse navbar-collapse d-flex justify-content-end">
                <ul class="nav navbar-nav navbar-user navbar-right">
                    <li id="usuario" class="nav-item">
                        <i class="mdi mdi-account mdi-18px"></i> {{ usuario }}
                    </li>
                    <li class="nav-item">
                        <a id="cerrar_sesion" href="{% url 'historial:cerrarSesion'%}">
                            <i class="mdi mdi-logout mdi-18px"></i> Cerrar sesión
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div id="navbar" class="col-xl-2 col-lg-2 col-md-2">
                    <ul id="navbar_vertical" class="nav flex-column">
                        <li class="nav-item">
                            <div id="acordeon_ficha" class="accordion">
                                <div class="card">
                                    <div id="headingOne" class="heading">
                                        <a class="nav-link collapsed titulo" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                            Ficha Médica
                                        </a>
                                    </div>
                                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#acordeon_ficha">
                                        {% if empleado.ocupacion == 'Doctor' or empleado.ocupacion == 'doctor' %}
                                        <a class="nav-link link" href="{% url 'historial:nuevaFichaMedica' empleado=id_empleado %}">Nuevo</a>
                                        {% endif %}
                                        <a class="nav-link link" href="{% url 'historial:consultarFicha' empleado=id_empleado %}">Consultar</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div id="acordeon_consulta" class="accordion">
                                <div class="card">
                                    <div id="headingTwo" class="heading">
                                        <a class="nav-link collapsed titulo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                            Consulta Médica
                                        </a>
                                    </div>
                                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#acordeon_consulta">
                                        <a class="nav-link link" href="#">Consultar</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div id="acordeon_atencion" class="accordion">
                                <div class="card">
                                    <div id="headingThree" class="heading">
                                        <a class="nav-link collapsed titulo" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                            Atención de Enfermería
                                        </a>
                                    </div>
                                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#acordeon_atencion">
                                        <a class="nav-link link" href="#">Consultar</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div id="contenido" class="col-xl-10 col-lg-10 col-md-10">
                    {% block contenido %}{% endblock %}
                </div>
            </div>
        </div>
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/base.js' %}" type="text/javascript"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

historialclinico/historial/templates/historial/error404.html
{% extends "historial/base.html" %}
{% block titulo %}Error 404{% endblock %}
{% block contenido %}
<h1>Error 404</h1>
{% endblock %}

historialclinico/historial/templates/historial/index.html
{% extends "historial/base.html" %}
{% load static %}
{% block titulo %}Historial médico{% endblock %}
{% block estilos %}
<link href="{% static 'css/index.css' %}" rel="stylesheet">
<link href="{% static 'css/jquery.dataTables.min.css' %}" rel="stylesheet">
{% endblock %}
{% block contenido %}
<div id="titulo_lista">
    <h4>Lista de empleados</h4>
</div>
<div>
    <p>Seleccione un empleado para realizar una acción: </p>
</div>
<div>
    <table id="tabla_empleados" class="cell-border hover">
        <thead>
            <tr>
                <th>Cédula</th>
                <th>Nombres</th>
                <th>Apellidos</th>
            </tr>
        </thead>
        <tbody>
        {% for empleado in listaEmpleados %}
            <tr id="{{ empleado.id }}">
                <td>{{ empleado.cedula }}</td>
                <td>{{ empleado.nombre }}</td>
                <td>{{ empleado.apellido }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <form id="formulario" action="{% url 'historial:infoEmpleado' %}" method="post">{% csrf_token %}
        <input id="id_empleado" name="id_empleado" value="{{ id_empleado }}" hidden>
    </form>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'js/index.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
{% endblock %}

historialclinico/historial/templates/historial/info_empleado.html
{% extends "historial/base.html" %}
{% load static %}
{% block titulo %}Historial médico{% endblock %}
{% block estilos %}
{% endblock %}
{% block contenido %}
<div id="titulo_lista">
    <h4>Información del empleado</h4>
</div>

{% endblock %}
{% block scripts %}
{% endblock %}